### ISSUE TITLE
Not using standard API

### ISSUE THREAD

**Issue by jpmeijers** [myDevicesIoT/Cayenne-Agent#2]
It would have been nicer if the agent used the [standard MQTT API](https://mydevices.com/cayenne/docs/bring-your-own-thing-api/), which is much better documented.

**Comment by jburhenn** [comment]
Thanks for the suggestion. We are actually planning on moving the agent to using MQTT at some point though we don't have a specific schedule for it yet. It may not use the current MQTT API though, so the communication packets may look similar to the current agent code.
