### ISSUE TITLE
Unable to save configuration 

### ISSUE THREAD

**Issue by greenb8** [myDevicesIoT/Cayenne-Agent#25]
Hey y’all, it’s my first time posting so I apologize if this has been solved already. 

I’m having an issue when I go into settings and try and enable i2c, 1 wire, etc. It doesn’t save my settings. I’m wondering if other people are having this issue?

Thanks so much,
-Nick

**Comment by jburhenn** [comment]
Are you making these changes within the Cayenne UI Settings page? If so, there might be some issues there. You may need to make the changes manually on the Pi itself using `sudo raspi-config` instead.

**Comment by greenb8** [comment]
It seems to be recognizing them now. Thank you a bunch,

**Comment by jburhenn** [comment]
Glad that's working for you now.
