### ISSUE TITLE
Invite code really necessary?

### ISSUE THREAD

**Issue by jpmeijers** [myDevicesIoT/Cayenne-Agent#3]
When installing the agent, you are asked for the invite code. When the software is run the invite code is exchanged for an AuthID. The AuthID is the same as the code in the URL of the dashboard. Ex:
https://cayenne.mydevices.com/cayenne/dashboard/raspberrypi/dd767fd0-4d07-11e7-b9b5-e1694237xxxx
The AuthID will then be `dd767fd0-4d07-11e7-b9b5-e1694237xxxx`.

Why do we need an invite code at all. Can't we just use the AuthID right through, from installation, config and execution of the agent?

Also it is impossible to retrieve the invite code after the agent has reported for the first time. This makes it impossible to reinstall your Pi without having to create a new device on Cayenne. This means that all historical data is lost for the device.

Refer to: http://community.mydevices.com/t/cayenne-linux-agent-open-sourced/3492/23

**Comment by jburhenn** [comment]
Yes, we are looking to replace the invite code when we switch to using MQTT for the agent. For now, if you need the invite code it should be available in the  `/etc/myDevices/AppSettings.ini` file. You may also want to save it off any time you add a new device just in case that file gets deleted or overwritten.
